-- Main Hyprland configuration

require("modules.scratchpads")
require("modules.monitors")
require("modules.programs")
require("modules.autostart")
require("modules.environment")
require("modules.permissions")
require("modules.lookandfeel.animations")
require("modules.lookandfeel.decoration")
require("modules.lookandfeel.general")
require("modules.layouts")
require("modules.misc")
require("modules.input")
require("modules.binds")
require("modules.windowrules")
