# Loads the Dynamic Colors from the Cache
source = ~/.cache/hyprlock_colors.conf

$font = Monospace

general {
    hide_cursor = false
}

animations {
    enabled = true
    bezier = linear, 1, 1, 0, 0
    animation = fadeIn, 1, 5, linear
    animation = fadeOut, 1, 5, linear
    animation = inputFieldDots, 1, 2, linear
}

background {
    monitor =
    # This path is automatically updated by the Python script on wallpaper change
    path = ~/Pictures/Wallpapers/wallhaven-oxzo55.png
    blur_passes = 3
    blur_size = 4
    contrast = 0.9
    brightness = 0.8
}

input-field {
    monitor =
    size = 280, 50
    outline_thickness = 2
    inner_color = rgba(20, 20, 30, 0.6)

    outer_color = $accent
    check_color = $accent
    fail_color = rgb(f38ba8)

    font_color = $text
    fade_on_empty = false
    rounding = 12

    font_family = $font
    placeholder_text = Password ...
    fail_text = $PAMFAIL$FPRINTFAIL

    dots_size = 0.3
    dots_spacing = 0.3

    position = 0, -60
    halign = center
    valign = center
}

# TIME
label {
    monitor =
    text = $TIME
    font_size = 80
    font_family = $font
    color = $text

    position = 0, 120
    halign = center
    valign = center
}

# DATE
label {
    monitor =
    text = cmd[update:60000] date +"%A, %d. %B %Y"
    font_size = 20
    font_family = $font
    color = $text

    position = 0, 45
    halign = center
    valign = center
}
